### PR TITLE
Fix image asset to show on setup screen

### PR DESCRIPTION
**Pull request by UrsKahmann**

### CODE REVIEW

**Review by FabioTacke — APPROVED** [review]
👍 Thanks!

**Comment by UrsKahmann** [comment]
@FabioTacke  I just noticed that in the new design [this screen](https://www.figma.com/file/upfFn94wpBq93Zkiy0B4gA/BundesIdent-Design?node-id=5011%3A38959&t=dKYG6SYNahfMYTB4-4) also has only the image with the three cards and without the pinletter.. Should I replace this, too while I am at it?

**Comment by FabioTacke** [comment]
Yes, good catch! You can just put that right into this PR as well.

**Review by FabioTacke — APPROVED** [review]
Looks great! 🤟

**Pull request merged**
